databases:
  - name: agri_connect_database
    plan: free
    databaseName: agri_connect_db
    user: agri_connect_user

services:
  - type: web
    plan: free
    name: agri_connect_api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agri_connect_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4