databases:
  - name: agri-connect-database
    plan: free
    databaseName: agri-connect-db
    user: agri-connect

services:
  - type: web
    plan: free
    name: agri-connect-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agri-connect-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4