# Generated by Django 5.0.4 on 2024-07-14 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('sub_county', models.CharField(max_length=50, verbose_name='Sub County')),
                ('geo_location', models.URLField(blank=True, max_length=1000, verbose_name='Maps URI')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Package Name')),
                ('description', models.TextField(verbose_name='Package Description')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duration (Days)')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pricing (KSH)')),
            ],
            options={
                'verbose_name': 'Subscription Package',
                'verbose_name_plural': 'Subscription Packages',
                'ordering': ['-duration'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('profile_picture', models.ImageField(default='user.png', upload_to='profiles/', verbose_name='Profile Picture')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='Phone Number')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Joined On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='InputAdvertisement',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.advertisement')),
            ],
            bases=('dashboard.advertisement',),
        ),
        migrations.CreateModel(
            name='ProduceAdvertisement',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.advertisement')),
            ],
            bases=('dashboard.advertisement',),
        ),
        migrations.CreateModel(
            name='ServiceAdvertisement',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.advertisement')),
            ],
            bases=('dashboard.advertisement',),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdvertisementPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to='ad-images/', verbose_name='Photo')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_photos', to='dashboard.advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Photo',
                'verbose_name_plural': 'Advertisement Photos',
            },
        ),
        migrations.CreateModel(
            name='BulkMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('recipients', models.CharField(choices=[('staff', 'Staff'), ('clients', 'Clients'), ('all', 'All')], default='staff', max_length=10, verbose_name='Send To')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Mail',
                'verbose_name_plural': 'Bulk Mails',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('image', models.ImageField(default='category.png', upload_to='categories/', verbose_name='Image')),
                ('classification', models.CharField(choices=[('FP', 'Farm Produce/Products'), ('SL', 'Service Listing')], default='FP', max_length=2, verbose_name='Classification')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Advertisement Category',
                'verbose_name_plural': 'Advertisement Categories',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='advertisement_category', to='dashboard.category'),
        ),
        migrations.CreateModel(
            name='CategoryRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='dashboard.category', verbose_name='Child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='dashboard.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category Relation',
                'verbose_name_plural': 'Category Relations',
                'ordering': ['parent', 'child'],
            },
        ),
        migrations.CreateModel(
            name='IndividualMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual Mail',
                'verbose_name_plural': 'Individual Mails',
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(default=uuid.uuid4)),
                ('file', models.FileField(upload_to='mail_attachments/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Mail Attachment',
                'verbose_name_plural': 'Mail Attachments',
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('token_key', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('is_api_call', models.BooleanField(default=False)),
                ('referer', models.URLField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(default='Pay Bill', max_length=50, verbose_name='Transaction Type')),
                ('trans_id', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('trans_time', models.DateTimeField(blank=True, null=True, verbose_name='Transaction Time')),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction Amount')),
                ('business_short_code', models.CharField(max_length=50, verbose_name='Business Short Code')),
                ('bill_ref_number', models.CharField(max_length=50, verbose_name='Bill Reference Number')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Organization Account Balance')),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50, verbose_name='Third Party Transaction ID')),
                ('msisdn', models.CharField(max_length=15, verbose_name='MSISDN')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mpesa_phone_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Review')),
                ('rating', models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='1', max_length=1, verbose_name='Rating')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subscriptionpackage')),
            ],
            options={
                'ordering': ['-active', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.advertisement')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subscription')),
            ],
            options={
                'verbose_name': 'Featured Advertisement',
                'verbose_name_plural': 'Featured Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offering', models.CharField(max_length=150, verbose_name='Offering')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_offerings', to='dashboard.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Package Offering',
                'verbose_name_plural': 'Package Offerings',
            },
        ),
        migrations.AddConstraint(
            model_name='categoryrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_category_relation'),
        ),
    ]
